In [2]:
import pandas as pd 
from sklearn.model_selection import train_test_split
import re

### Load dataset and simple overview

In [8]:
df = pd.read_csv("../data/email_origin.csv")
df.head()

   label                                             origin
0      0  Subject: re : wolf - reply - reply - reply\n\n...
1      0  Subject: hilcorp old ocean\n\ni have continued...
2      0  Subject: merchanting metals update\n\nseveral ...
3      0  Subject: meter 6461 , concorde churchill\n\non...
4      0  Subject: weekly deal report\n\nattached is the...

In [9]:
df["origin"][0]

"Subject: re : wolf - reply - reply - reply\n\nwrong bill grace / i ' ll forward .\n- - - - - original message - - - - -\nfrom : rodriguez , grace\nsent : friday , june 29 , 2001 9 : 23 am\nto : fitzpatrick , amy ; williams , bill\nsubject : re : wolf - reply - reply - reply\nplease let me know who you would like to interview darrin , and when .\nthanks !\n- grace\n- - - - - original message - - - - -\nfrom : fitzpatrick , amy\nsent : friday , june 29 , 2001 7 : 35 am\nto : rodriguez , grace\nsubject : fw : wolf - reply - reply - reply\ngrace -\nplease schedule an interview for this candidate to meet with me , bill and anyone else that bill recommends . we need to treat this one ' right ' - he is the brother of a vp in houston . . . . . . . .\nthanks !\namy\n- - - - - original message - - - - -\nfrom : wolfe , greg\nsent : friday , june 29 , 2001 6 : 53 am\nto : williams iii , bill ; fitzpatrick , amy\nsubject : fw : wolf - reply - reply - reply\nbill / amy :\nattached is darrin presto ' s resume . i have met darrin in the past and based upon my first impression he would be a good candidate for real time . please set up an interview .\nthanks\n- - - - - original message - - - - -\nfrom : presto , kevin m .\nsent : friday , june 29 , 2001 5 : 46 am\nto : wolfe , greg\nsubject : fw : wolf - reply - reply - reply\ncover letter and resume from my brother are attached .\n- - - - - original message - - - - -\nfrom : darrin presto @ enron [ mailto : imceanotes - darrin + 20 presto + 20 + 3 cdarrin + 5 fpresto + 40 rsd + 2 eedu + 3 e + 40 enron @ enron . com ]\nsent : thursday , june 28 , 2001 6 : 37 pm\nto : presto , kevin m .\nsubject : re : wolf - reply - reply - reply\nkev ,\nhere is everything . keep me posted .\n- enronc ~ 1 . doc >\n- enronr ~ 1 . doc >\n- enronr ~ 2 . doc >"

In [4]:
df.shape

(33702, 2)

In [1]:
d = pd.read_csv("../data/email_origin.csv")
d.head()

NameError: name 'pd' is not defined

In [27]:
d["label"].value_counts()

label
1    17157
0    16545
Name: count, dtype: int64

In [5]:
df.isnull().sum()

Unnamed: 0    0
Body          1
Label         0
dtype: int64

In [6]:
df[df["Body"].isnull()]

     Unnamed: 0 Body  Label
328         328  NaN      1

In [23]:
df["Label"].value_counts()

Label
0    4150
1    1895
Name: count, dtype: int64

In [24]:
4150/1895

2.1899736147757256

In [18]:
df.iloc[:,1:-1]

                                                   Body
0     \nSave up to 70% on Life Insurance.\nWhy Spend...
1     1) Fight The Risk of Cancer!\nhttp://www.adcli...
2     1) Fight The Risk of Cancer!\nhttp://www.adcli...
3     ##############################################...
4     I thought you might like these:\n1) Slim Down ...
...                                                 ...
6041                                              empty
6042                    ___           ___           ...
6043  IN THIS ISSUE:01. Readers write\n02. Extension...
6044                                              empty
6045                                              empty

[6045 rows x 1 columns]

In [22]:
a = [1,2,3,4]
a[1:-1]

[2, 3]

In [7]:
df.dropna(inplace=True)

In [4]:
df["Label"].value_counts()

Label
0    4150
1    1896
Name: count, dtype: int64

In [8]:
df.to_csv("../data/spam_or_not.csv")

In [10]:
d = pd.read_csv("../data/spam_or_not.csv")
d.shape

(6045, 4)

In [5]:
df.shape

(6046, 3)

In [ ]:
X = df["text"]
y = df["label"]

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [ ]:
len(X_test)

In [ ]:
X_test

In [ ]:
len(X_test)

In [ ]:
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
stp_words = stopwords.words('english')
lemitizer = WordNetLemmatizer()
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
len(X_test)

In [ ]:
def convert_into_token(data):
    tokens = []
    for x in data:
        token = word_tokenize(x)
        clean_token = []
        for word in token:
            w = re.sub(r'[^a-zA-Z0-9]','',word)
            if w.lower() not in stp_words and w != "":
                lemitize = lemitizer.lemmatize(w)
                clean_token.append(lemitize)
        tokens.append(clean_token)
    return tokens

In [ ]:
X_train_tokens = convert_into_token(X_train)
X_test_tokens = convert_into_token(X_test)

In [ ]:
def text_to_vector_tfidf(tokens):
        """
        --> Convert tokens into TF-IDF vectors and return numpy array
        """
        try:
            # Convert token list into sentence
            corpus = []

            for sentence in tokens:
                corpus.append(" ".join(sentence))

            # TF-IDF Vectorizer
            tfidf = TfidfVectorizer(
                max_features=3000
            )
            print(corpus)
            # Fit and transform
            vector = tfidf.fit_transform(corpus)
            return vector.toarray()
        except Exception as e:
                print(e)

In [ ]:
X_train_vec = text_to_vector_tfidf(X_train_tokens)
X_test_vec = text_to_vector_tfidf(X_test_tokens)

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC 
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier,AdaBoostClassifier,GradientBoostingClassifier
from sklearn.metrics import accuracy_score


def find_best_model_and_train(X_train,y_train,X_test,y_test):
        """
        --> Find the best model
        --> train and return 
        """
        try:
            models = {
                "LogisticRegression":LogisticRegression(verbose=1),
                "SVC":SVC(verbose=1),
                "GaussianNB":GaussianNB(),
                "DecisionTreeClassifier":DecisionTreeClassifier(),
                "RandomForestClassifier":RandomForestClassifier(),
                "AdaBoostClassifier":AdaBoostClassifier(),
                "GradientBoostingClassifier":GradientBoostingClassifier()
            }
            best_model = None
            best_score = 0
            best_model_name = ""

            for name, model in models.items():
                model.fit(X_train, y_train)

                y_pred = model.predict(X_test)

                score = accuracy_score(y_test, y_pred)
                print(f"{name}:{score}")
                # Finding best model
                if score > best_score:
                    best_score = score
                    best_model = model
                    best_model_name = name
            print(f"{best_model_name}:{best_score}")
            return best_model
        except Exception as e:
            print(e)

In [ ]:
from gensim.models import Word2Vec

model = Word2Vec(tokens)

In [ ]:
import numpy as np

def sentence_vector(sentence, model):
    vectors = []

    for word in sentence:
        if word in model.wv:
            vectors.append(model.wv[word])

    if len(vectors) == 0:
        return np.zeros(model.vector_size)

    return np.mean(vectors, axis=0)

In [ ]:
import pandas as pd 
dd = pd.read_csv("../Artifacts/05_18_2026_16_27_31/data_ingestion/ingested/test.csv")
dd.shape